name = "totp-manager-api"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "TOTP_STORE", id = "你的kv空间id" },
]



[vars]
ENVIRONMENT = "production"
GITHUB_CLIENT_ID="你的github应用id"
GITHUB_CLIENT_SECRET="你的github应用密钥"
JWT_SECRET="你的jwt密钥"
ENCRYPTION_KEY = "你的加密密钥"
//部署完后要改成对应的worker域名
GITHUB_REDIRECT_URI = "http://localhost:8080/api/github/callback"
//部署完后要改成对应的pages域名
FRONTEND_URL = "http://localhost:3000"

[dev]
port = 8080

[build]
command = "pnpm install"
[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[build.upload.module_rules]
"bcryptjs" = { type = "npm" }